name: Check signed commits in PR 
on: pull_request

jobs:
  build:
    name: Check signed commits in PR 
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check signed commits in PR
        uses: ./
